"""Emit a complete, inspectable ca65 program for an NROM-128 game.

Python runs only while this source is being generated. The generated controller
checks and action instructions run on the NES once per completed video frame.
"""

from collections.abc import Sequence

from .model import Event, Move, SetPosition, SetTile, Sprite, Trigger


LINKER_CONFIG = """# NROM-128: one mirrored 16 KiB PRG bank and one 8 KiB CHR bank.
MEMORY {
    ZP:     start = $0000, size = $0100, type = rw;
    RAM:    start = $0300, size = $0500, type = rw;
    HEADER: start = $0000, size = $0010, type = ro, file = %O;
    PRG:    start = $C000, size = $4000, type = ro, file = %O,
            fill = yes, fillval = $FF;
    CHR:    start = $0000, size = $2000, type = ro, file = %O;
}
SEGMENTS {
    ZEROPAGE: load = ZP,     type = zp;
    BSS:      load = RAM,    type = bss, optional = yes;
    HEADER:   load = HEADER, type = ro;
    CODE:     load = PRG,    type = ro;
    RODATA:   load = PRG,    type = ro;
    VECTORS:  load = PRG,    type = ro, start = $FFFA;
    CHARS:    load = CHR,    type = ro;
}
"""


def _byte_lines(data: bytes) -> list[str]:
    return [
        "    .byte " + ", ".join(f"${value:02X}" for value in data[offset : offset + 16])
        for offset in range(0, len(data), 16)
    ]


def _action_lines(action: Move | SetPosition | SetTile) -> list[str]:
    base = 0x0200 + 4 * action.sprite.index
    if isinstance(action, Move):
        lines = []
        for address, delta in ((base + 3, action.dx), (base, action.dy)):
            if delta:
                lines.extend(
                    [
                        f"    lda ${address:04X}",
                        "    clc",
                        f"    adc #${delta & 0xFF:02X}",
                        f"    sta ${address:04X}",
                    ]
                )
        return lines
    if isinstance(action, SetPosition):
        return [
            f"    lda #${action.x:02X}",
            f"    sta ${base + 3:04X}",
            f"    lda #${action.y:02X}",
            f"    sta ${base:04X}",
        ]
    if isinstance(action, SetTile):
        return [f"    lda #${action.tile:02X}", f"    sta ${base + 1:04X}"]
    raise TypeError(f"Unsupported runtime action: {type(action).__name__}")


def generate_assembly(
    *,
    nametable: bytes,
    chr_data: bytes,
    palette: bytes,
    sprites: Sequence[Sprite],
    events: Sequence[Event],
) -> str:
    """Generate self-contained ca65 source with embedded graphics and scene data.

    The nametable includes its 64-byte attribute table. Sprite positions use raw
    OAM coordinates; the PPU displays a sprite one scanline below its Y value.
    """
    for name, data, expected in (
        ("nametable", nametable, 1024),
        ("chr_data", chr_data, 8192),
        ("palette", palette, 32),
    ):
        if len(data) != expected:
            raise ValueError(f"{name} must contain exactly {expected} bytes")

    # Y=$FF hides an unused sprite. Initialize the entire page so DMA is always
    # safe, including before the first gameplay update has run.
    initial_oam = bytearray([0xFF] * 256)
    for sprite in sprites:
        attribute = (
            sprite.palette
            | (0x20 if sprite.behind_background else 0)
            | (0x40 if sprite.flip_horizontal else 0)
            | (0x80 if sprite.flip_vertical else 0)
        )
        offset = sprite.index * 4
        initial_oam[offset : offset + 4] = bytes(
            (sprite.y, sprite.tile, attribute, sprite.x)
        )

    lines = [
        "; Generated by py3nes. Assemble with ca65 and link with the supplied config.",
        "; Target: NTSC NES, mapper 0, NROM-128, horizontal nametable mirroring.",
        '.setcpu "6502"',
        "",
        "PPUCTRL   = $2000",
        "PPUMASK   = $2001",
        "PPUSTATUS = $2002",
        "OAMADDR   = $2003",
        "PPUSCROLL = $2005",
        "PPUADDR   = $2006",
        "PPUDATA   = $2007",
        "DMCCTRL   = $4010",
        "OAMDMA    = $4014",
        "APUSTATUS = $4015",
        "JOYPAD1   = $4016",
        "APUFRAME  = $4017",
        "",
        '.segment "HEADER"',
        "    .byte $4E, $45, $53, $1A ; iNES signature",
        "    .byte 1, 1, 0, 0       ; 16 KiB PRG, 8 KiB CHR, mapper 0",
        "    .byte 0, 0, 0, 0, 0, 0, 0, 0",
        "",
        '.segment "ZEROPAGE"',
        ".exportzp controller_held, controller_pressed, controller_previous, frame_ready",
        "controller_held:     .res 1",
        "controller_pressed:  .res 1",
        "controller_previous: .res 1",
        "frame_ready:         .res 1",
        "",
        '.segment "CODE"',
        ".export reset, nmi, irq, main_loop, read_controller, update_events",
        "",
        "reset:",
        "    sei",
        "    cld",
        "    ldx #$FF",
        "    txs",
        "    inx",
        "    stx PPUCTRL       ; disable NMI while initializing the scene",
        "    stx PPUMASK       ; disable rendering",
        "    stx DMCCTRL       ; disable DMC IRQ",
        "    stx APUSTATUS     ; disable all audio channels and DMC DMA",
        "    stx frame_ready",
        "    lda #$40",
        "    sta APUFRAME      ; inhibit APU frame IRQ",
        "    bit PPUSTATUS     ; acknowledge old vblank and reset address latch",
        "",
        "; The PPU ignores several writes during power-up; wait two vblanks.",
        "wait_vblank_1:",
        "    bit PPUSTATUS",
        "    bpl wait_vblank_1",
        "    lda #$00",
        "    tax",
        "clear_ram:",
        "    sta $0000,x",
        "    sta $0100,x",
        "    sta $0200,x",
        "    sta $0300,x",
        "    sta $0400,x",
        "    sta $0500,x",
        "    sta $0600,x",
        "    sta $0700,x",
        "    inx",
        "    bne clear_ram",
        "wait_vblank_2:",
        "    bit PPUSTATUS",
        "    bpl wait_vblank_2",
        "",
        "; Explicitly establish PPU state after its power-up write lock ends.",
        "    lda #$00",
        "    sta PPUCTRL       ; increment 1, nametable 0, 8x8 sprites, CHR table 0",
        "    sta PPUMASK",
        "    bit PPUSTATUS",
        "    lda #$3F",
        "    sta PPUADDR",
        "    lda #$00",
        "    sta PPUADDR",
        "    ldx #$00",
        "load_palette:",
        "    lda initial_palette,x",
        "    sta PPUDATA",
        "    inx",
        "    cpx #$20",
        "    bne load_palette",
        "",
        "    lda #$20",
        "    sta PPUADDR",
        "    lda #$00",
        "    sta PPUADDR",
        "    ldx #$00",
    ]
    for page in range(4):
        lines.extend(
            [
                f"load_nametable_{page}:",
                f"    lda initial_nametable + ${page * 256:04X},x",
                "    sta PPUDATA",
                "    inx",
                f"    bne load_nametable_{page}",
            ]
        )
    lines.extend(
        [
            "",
            "load_initial_oam:",
            "    lda initial_oam,x",
            "    sta $0200,x",
            "    inx",
            "    bne load_initial_oam",
            "",
            "; Start display during vblank, after initializing every OAM entry.",
            "wait_vblank_start:",
            "    bit PPUSTATUS",
            "    bpl wait_vblank_start",
            "    lda #$00",
            "    sta OAMADDR",
            "    lda #$02",
            "    sta OAMDMA",
            "    lda #$00",
            "    sta PPUSCROLL",
            "    sta PPUSCROLL",
            "    lda #$01",
            "    sta frame_ready",
            "    lda #$80",
            "    sta PPUCTRL       ; enable vblank NMI, both CHR tables at $0000",
            "    lda #$1E",
            "    sta PPUMASK       ; background and sprites, including leftmost 8 px",
            "",
            "; Only main writes OAM RAM. Only NMI commits a complete buffer.",
            "; If an update takes longer than a frame, NMI skips DMA until ready.",
            "main_loop:",
            "    lda frame_ready",
            "    bne main_loop",
            "    jsr read_controller",
            "    jsr update_events",
            "    lda #$01",
            "    sta frame_ready",
            "    jmp main_loop",
            "",
            "read_controller:",
            "    lda controller_held",
            "    sta controller_previous",
            "    lda #$01",
            "    sta JOYPAD1",
            "    lda #$00",
            "    sta JOYPAD1",
            "    sta controller_held",
            "    ldx #$08",
            "read_controller_bit:",
            "    lda JOYPAD1",
            "    lsr a",
            "    rol controller_held",
            "    dex",
            "    bne read_controller_bit",
            "    lda controller_previous",
            "    eor #$FF",
            "    and controller_held",
            "    sta controller_pressed",
            "    rts",
            "",
            "update_events:",
        ]
    )
    for index, event in enumerate(events):
        if event.trigger != Trigger.FRAME:
            state = {
                Trigger.HELD: "controller_held",
                Trigger.PRESSED: "controller_pressed",
            }[event.trigger]
            lines.extend(
                [
                    f"    lda {state}",
                    f"    and #${int(event.button):02X}",
                    f"    bne event_{index}_run",
                    f"    jmp event_{index}_done",
                    f"event_{index}_run:",
                ]
            )
        for action in event.actions:
            lines.extend(_action_lines(action))
        if event.trigger != Trigger.FRAME:
            lines.append(f"event_{index}_done:")
    lines.extend(
        [
            "    rts",
            "",
            "nmi:",
            "    pha",
            "    txa",
            "    pha",
            "    tya",
            "    pha",
            "    lda frame_ready",
            "    beq nmi_scroll",
            "    lda #$00",
            "    sta OAMADDR",
            "    lda #$02",
            "    sta OAMDMA",
            "    lda #$00",
            "    sta frame_ready",
            "nmi_scroll:",
            "    bit PPUSTATUS",
            "    lda #$00",
            "    sta PPUSCROLL",
            "    sta PPUSCROLL",
            "    pla",
            "    tay",
            "    pla",
            "    tax",
            "    pla",
            "    rti",
            "",
            "irq:",
            "    rti",
            "",
            '.segment "RODATA"',
            "initial_palette:",
            *_byte_lines(palette),
            "initial_nametable:",
            *_byte_lines(nametable),
            "initial_oam:",
            *_byte_lines(bytes(initial_oam)),
            "",
            '.segment "VECTORS"',
            "    .word nmi, reset, irq",
            "",
            '.segment "CHARS"',
            "chr_tiles:",
            *_byte_lines(chr_data),
            "",
        ]
    )
    return "\n".join(lines)
